# permissions for end users to edit configrestarts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmap-restart
    app.kubernetes.io/managed-by: kustomize
  name: configrestart-editor-role
rules:
- apiGroups:
  - opsapp.someapp.cn
  resources:
  - configrestarts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opsapp.someapp.cn
  resources:
  - configrestarts/status
  verbs:
  - get
