---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opsapp.someapp.cn
  resources:
  - configrestarts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opsapp.someapp.cn
  resources:
  - configrestarts/finalizers
  verbs:
  - update
- apiGroups:
  - opsapp.someapp.cn
  resources:
  - configrestarts/status
  verbs:
  - get
  - patch
  - update
